### PR TITLE
Update Makefile and other files accordingly

### PR DESCRIPTION
**Pull request by RNAer**
also add readme.md for documentation.

ready for review

### CODE REVIEW

**Comment by mortonjt** [comment]
First pass through.  So far so good.

**Comment by RNAer** [comment]
let's merge it if ok?

**Comment by mortonjt** [comment]
I'm now getting quite a few test errors when I try to run this ...

**Comment by RNAer** [comment]
could u post it? let me restart the travis to test again.

**Comment by mortonjt** [comment]
```bash
======================================================================
ERROR: test_hmmpress_hmm_exist (test_hmmer.HMMPressTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/tests/test_hmmer.py", line 79, in test_hmmpress_hmm_exist
    with self.assertRaisesRegex(
AttributeError: 'HMMPressTests' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: test_hmmscan_fasta_wrong_input (test_hmmer.HMMScanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/tests/test_hmmer.py", line 56, in test_hmmscan_fasta_wrong_input
    with self.assertRaisesRegex(
AttributeError: 'HMMScanTests' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: test_cmpress_cm_exist (test_infernal.CMPressTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/tests/test_infernal.py", line 95, in test_cmpress_cm_exist
    with self.assertRaisesRegex(
AttributeError: 'CMPressTests' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: test_cmscan_fasta_wrong_input (test_infernal.CMScanTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/tests/test_infernal.py", line 69, in test_cmscan_fasta_wrong_input
    with self.assertRaisesRegex(
AttributeError: 'CMScanTests' object has no attribute 'assertRaisesRegex'

======================================================================
ERROR: test_predict_genes (test_prodigal.ProdigalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/tests/test_prodigal.py", line 82, in test_predict_genes
    res = predict_genes(fp, self.temp_dir, prefix, params)
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/prodigal.py", line 122, in predict_genes
    makedirs(out_dir, exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

======================================================================
ERROR: test_predict_genes_wrong_input (test_prodigal.ProdigalTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mortonjt/Documents/UCSD/research/workspace/micronota/micronota/bfillings/tests/test_prodigal.py", line 71, in test_predict_genes_wrong_input
    with self.assertRaisesRegex(
AttributeError: 'ProdigalTests' object has no attribute 'assertRaisesRegex'
```

**Comment by RNAer** [comment]
i don't have any problem of that. do you have a clean environment? It seems there are problems with your `unittest` module

**Comment by mortonjt** [comment]
Had wonky settings.  Consider this merged.

**Pull request merged**
