### PR TITLE
improve .travis.yml

### PR DESCRIPTION
**Pull request by RNAer**

### CODE REVIEW

**Comment by mortonjt** [comment]
What's required to get this merged?

**Comment by RNAer** [comment]
nothing. that's ready.

**Comment by mortonjt** [comment]
Ok.  I'll merge it once merge conflicts have been resolved

**Comment by RNAer** [comment]
what merge conflict?

**Comment by mortonjt** [comment]
This branch isn't up to date with master.  It need to be fetched and pulled before a merge can happen

**Comment by mortonjt** [comment]
:+1:

**Pull request merged**
