### PR TITLE
SAM parser

### PR DESCRIPTION
**Pull request by mortonjt**
This is required for the aligner cache.

### CODE REVIEW

**Comment by mortonjt** [comment]
Ready for review once tests pass.

**Comment by mortonjt** [comment]
Adding in the blank file.

@RNAer, the other tests that are failing are completely independent of this PR.  Do you know what is happening?

**Comment by RNAer** [comment]
did you pull the latest from biocore/micronota?

**Comment by mortonjt** [comment]
Some branch confusions.  Closing this in favor for #58

**Pull request closed without merging**
