### PR TITLE
Add travis and coverall integration

### PR DESCRIPTION
**Pull request by RNAer**
also add badges to readme.rst

### CODE REVIEW

**Comment by wasade** [comment]
:+1:

**Comment by mortonjt** [comment]
Is this ready to go?  (I don't have merge permissions btw)

**Comment by RNAer** [comment]
Just asked Yoshiki for permission. You should be able to merge. before this
one, would you mind reviewing the other pull request (#4) and merge it if
no problem ?

**Comment by mortonjt** [comment]
On it

**Comment by RNAer** [comment]
@mortonjt @wasade , updates ready for review/merge

**Pull request merged**
